### ISSUE TITLE
Invalid library found 

### ISSUE THREAD

**Issue by AusUser5** [sparkfun/LTC4150_Coulomb_Counter_BOB#1]
Adding the zip to Ardunino 1.6.11 failed.

Adding library manually showed error "invalid library found"

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. I came across your question when browsing our issues. It looks like you are trying to add the example code to your Arduino library. I do not believe that will work (as you have seen) because the example code is not structured as a library. 

If you are still wondering, you just need to unzip the files and open the individual &#42;.ino examples in the Arduino IDE.
