### ISSUE TITLE
Three Coulomb counters with all different values

### ISSUE THREAD

**Issue by arrowmax08** [sparkfun/LTC4150_Coulomb_Counter_BOB#4]
Hi, 

I tested three LTC4150's that all print different values.

The first value will be incorrect, because we have no previous start time to compare the delay between interrupts with. The INT pin will pulse low every time 0.614 coulombs passes through the device. So you can say that all coulomb counters with the same setup must print very similar values. 

With two AA batteries connected to the IN port of the Coulomb counter I get around the following values:

Coulomb counter 1: prints "1.30 mA"
Coulomb counter 2: prints "2.15 mA"
Coulomb counter 3: prints "1.80 mA"

Are they not calibrated right?

**Comment by mgrusin** [comment]
Good question and interesting results.

To be honest, determining instantaneous power consumption from the timing of the coulomb interrupt, especially for low currents like the above, is a bit of a parlor trick. Even though the number of INT pulses over time should be accurate, calculating instantaneous power consumption by measuring the time between them is subject to numerous measurement and rounding errors (especially if you're using the polled code rather than interrupt-driven). Your test setup is also important; it's better to measure a fixed resistor (the same one for all three boards) than a dynamic load like a processor or LED; and to use a fixed linear power source rather than a battery, which can change voltage during use and recovery. And you're right; I've never looked at the statistics for a large number of counters, but there could be manufacturing variations in the chips and sense resistors, etc.

 If you absolutely require consistent numbers between all your boards, the best solution is always to calibrate them individually using the best test setup you can manage. This usually means a fixed (linear) power source and load resistor.  Per the above I'd measure a large number of INT pulses over time rather than the individual timing. You'd then apply the results to the individual bits of software doing the reading. This is often not worth the trouble for a few percent difference, but if one or more of your boards is obviously misbehaving please do contact our tech support department for replacement. 

Hope this helps, thanks for asking!
